<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
 
  <xsd:element name="Order">
    <xsd:complexType>
      <xsd:sequence>
 
        <!-- Order Info -->
        <xsd:element name="orderNumber" type="xsd:string"/>
        <xsd:element name="orderDate" type="xsd:string"/>
 
        <!-- Customer Info -->
        <xsd:element name="customerInfo">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="customerId" type="xsd:string"/>
              <xsd:element name="fullName" type="xsd:string"/>
              <xsd:element name="contact">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="emailAddress" type="xsd:string"/>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
 
        <!-- Items -->
        <xsd:element name="items">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="product" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="id" type="xsd:string"/>
                    <xsd:element name="name" type="xsd:string"/>
                    <xsd:element name="qty" type="xsd:int"/>
                    <xsd:element name="unitPrice" type="xsd:decimal"/>
                    <xsd:element name="totalPrice" type="xsd:decimal"/>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
 
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
 
</xsd:schema>
